TICKET FOUR
charli353/News-Database pull request #4
Opened 2023-06-26 15:10 UTC by charli353

2023-06-26 15:25 UTC, Slyose reviewed
Great stuff so far. Missed out on one error case, please address the feedback and resubmit your nchelp pr afterwards

2023-06-26 15:25 UTC, Slyose commented on __tests__/app.test.js
> +            expect(obj).toHaveProperty("article_id", expect.any(Number));
You can expect this id to be 5 exactly, since that's the article you're requesting

2023-06-26 15:25 UTC, Slyose commented on __tests__/app.test.js
> +          body.articles.forEach((obj) => {
Descriptive names are always better!
obj -> article

2023-06-26 15:25 UTC, Slyose commented on __tests__/app.test.js
> +        expect(body).toEqual({Error: "400, Invalid ID"})
This ID is invalid because the number is so large (numeric overflow)

But what about a valid ID that isn't found?
e.g. /api/articles/1000

_tip: this wont be a psql error! You'll have to put a custom error handler in_

2023-06-27 08:10 UTC, NRMSMITH requested changes
Error handling needs to be re-looked at :) Please resubmit once done 😄

2023-06-27 08:10 UTC, NRMSMITH commented on __tests__/app.test.js
> +        });
Great job making sure that there's a length before the forEach -  I think this should be refactored into a .toMatchObject or .objectContaining, simply because later on you will need more flexibility with this test!

2023-06-27 08:10 UTC, NRMSMITH commented on db/controllers/articles.controller.js
> +const fs = require('fs/promises')
You don't need to use fs/promises :) I would take this out as it could be misleading for a senior dev to read :)

2023-06-27 08:10 UTC, NRMSMITH commented on __tests__/app.test.js
> +        expect(body).toEqual({"articles" : { Error: 'ID Does Not Exist' }})
After the lecture today - you will have to redo this test in particular - it should be a Promise.reject in the model, then custom error handling in the app or error.controller :)

2023-06-27 09:04 UTC, Dutton1990 approved these changes
Nice job with the refactor Charlie! You can merge this one now 👍

2023-06-27 09:05 UTC, merged