TICKET FIVE
charli353/News-Database pull request #5
Opened 2023-06-27 13:25 UTC by charli353

2023-06-27 15:32 UTC, EddTheDuck requested changes
Please read my comments and make the required changes before submitting another PR.

2023-06-27 15:32 UTC, EddTheDuck commented on __tests__/app.test.js
> +      });
This is an interesting way of checking how it's sorted - have a look into jest sorted and refactor when you get chance to make it more readable.

https://www.npmjs.com/package/jest-sorted

2023-06-27 15:32 UTC, EddTheDuck commented on __tests__/app.test.js
> +      })
Unless you're testing for something more specific like an error message, this test as it stands is only testing that express is working as intended. Which is not for us to test.

If you wanted to test for a generic bad path it should be in it's own describe block.

2023-06-27 15:32 UTC, EddTheDuck commented on db/app.js
> +// there should not be a body property present on any of the article objects.
Remove comented out code before submitting a PR

2023-06-27 15:32 UTC, EddTheDuck commented on db/app.js
> +    console.log('nexting')
remove console.logs - what is this app.use doing?

2023-06-27 15:32 UTC, EddTheDuck commented on db/controllers/articles.controller.js
> +        res.status(200).send(articles)
This should respond with the data on an appropriate key eg articles

2023-06-27 15:32 UTC, EddTheDuck commented on db/models/articles.model.js
> +
What is this function and what is it doing?

2023-06-27 15:32 UTC, EddTheDuck commented on db/seeds/seed.js
> +
Generally speaking you should not change the seed file and more specifically you should not be creating a table that contains information that is derivable from other information. We have access to all the comments in the  comments table, that means we can figure out how many comments each article has by looking in there.

Look at using an aggregate function to do this (How we did it together.)

**This seed function needs reverting to how it was before proceeding any further.**

2023-06-27 15:32 UTC, EddTheDuck commented on db/app.js
>  const e = require('express')
Get rid of this as it isn't doing anything

2023-06-28 08:29 UTC, NRMSMITH approved these changes
Much cleaner Charlie - well done!

2023-06-28 08:29 UTC, NRMSMITH commented on __tests__/app.test.js
> +})
👍

2023-06-28 08:29 UTC, NRMSMITH commented on db/models/articles.model.js
> +}
using letters instead of the full table name is really advanced psql stuff - very cool!

2023-06-28 08:29 UTC, NRMSMITH commented on db/models/articles.model.js
> +            console.log(rows)
make sure you get rid of those errant console.logs() !

2023-06-28 08:32 UTC, merged